### ISSUE TITLE
Media Player Entity not updating once in HA - its on a seperate VLAN

### ISSUE THREAD

**Issue by xkoldxx** [lululombard/tesmart-lan-homeassistant#35]
Set this up today and i got the media player entity to appear but i cannot get that TESMart to change source

**Comment by xkoldxx** [comment]
This error originated from a custom integration.

Logger: homeassistant.util.async_
Source: custom_components/tesmart_lan/media_player.py:171
integration: tesmart_lan (documentation, issues)
First occurred: 23:18:30 (1 occurrences)
Last logged: 23:18:30

Detected blocking call to sleep inside the event loop by custom integration 'tesmart_lan' at custom_components/tesmart_lan/media_player.py, line 171: time.sleep(0.2), please create a bug report at https://github.com/lululombard/tesmart-lan-homeassistant/issues

**Comment by xkoldxx** [comment]
looks like the integration itself isnt starting any feedback?

**Comment by notmayo** [comment]
I'm having a similar issue, however, all my devices are on the same VLAN. I can do a call service or use the more-info panel to change sources, but that update is not sent to the switch. I can control the beep setting through either more-info or service calls. The official controller.exe app can connect over LAN, and change settings and sources.

**Comment by barndawgie** [comment]
I just opened #41 but I'm thinking this is the same thing. I also see that error in the logs on startup.

**Comment by barndawgie** [comment]
I have a fix for this in PR, but I'm not sure if this repo is being actively maintained. You can pull it from my fork if you'd like to try it out. I may detach my fork if I don't see traction from the owners here.

**Comment by barndawgie** [comment]
Yes - just discovered that. Too bad I did two days of debugging here 🤣
