### ISSUE TITLE
Core 2025 Changes

### ISSUE THREAD

**Issue by wlraider70** [lululombard/tesmart-lan-homeassistant#39]
I'm getting error and warnings in my log.
It looks it wont load. That could be a "me" error, but the second warnings makes me think that its not me.

**Error1:**

Logger: homeassistant.helpers.service
Source: /usr/src/homeassistant/homeassistant/helpers/service.py:712
First occurred: 8:20:45 PM (1 occurrences)
Last logged: 8:20:45 PM

Failed to load integration: tesmart_lan
NoneType: None

**Error 2**

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1628
First occurred: 8:20:44 PM (2 occurrences)
Last logged: 8:20:44 PM

Entity media_player.tesmart_hdmi_switch (<class 'custom_components.tesmart_lan.media_player.TesmartLan'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.SELECT_SOURCE|SELECT_SOUND_MODE: 67584>, please create a bug report at https://github.com/lululombard/tesmart-lan-homeassistant/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by Jaharmi** [comment]
I am also seeing Error 1 and 2 (listed as a warning).

For this integration on HA 2024.12, I see 3 warnings and a “Failed to load integration” error.
